---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: src/**/*
  exclude: src/blog/**/*
- type: directory
  path: src/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: src/.vuepress/public/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
